name: Default Branch Tests and Coverage

on:
  push:
    branches:
      - main

jobs:
  pull-request-run-tests:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-jdk
      - uses: ./.github/actions/cache-gradle
      - uses: ./.github/actions/run-tests
        with:
          codecov_token: ${{ secrets.CODECOV }}