name: Publish to GitHub Packages (npm)

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew jsBrowserProductionWebpack

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hitoshura25'

      - name: Configure npm
        run: |
          cd build/js/packages/mpo-api-search-kmp
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm config set @hitoshura25:registry https://npm.pkg.github.com

      - name: Update package.json
        run: |
          cd build/js/packages/mpo-api-search-kmp
          jq '.name="@hitoshura25/mpo-api-search-kmp" | .publishConfig={"registry": "https://npm.pkg.github.com"} | .repository={"type": "git", "url": "git+https://github.com/hitoshura25/mpo-api-search-kmp.git"}' package.json > temp.json
          mv temp.json package.json

      - name: Publish to GitHub Packages
        run: |
          cd build/js/packages/mpo-api-search-kmp
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}