name: Run tests on main branch and publish pre-release NPM

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-jdk.yml
      - uses: ./.github/workflows/cache-gradle.yml
      - uses: ./.github/workflows/run-tests.yml