on:
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]

jobs:
  prepare-next-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID_GITHUB }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: main
          fetch-depth: 0

      - uses: ./.github/actions/increment-version
        with:
          version_type: 'rc'
          github_push_token: ${{ steps.app-token.outputs.token }}
