name: Publish to NPM

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Packages
        run: |
          cd build/js/packages/@hitoshura25/mpo-api-search-kmp
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}