name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  setup-jdk:
    needs: checkout
    uses: ./.github/workflows/setup-jdk.yml

  cach-gradle:
    needs: setup-jdk
    uses: ./.github/workflows/cache-gradle.yml

  run-tests:
    needs: cache-gradle
    uses: ./.github/workflows/run-tests.yml