name: Pull Request Tests and Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request-run-tests:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID_GITHUB }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - uses: ./.github/actions/setup-jdk
      - uses: ./.github/actions/cache-gradle
      - uses: ./.github/actions/run-tests
        with:
          codecov_token: ${{ secrets.CODECOV }}
      - uses: ./.github/actions/build-js
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/publish-npm-package
        with:
          publish_auth_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/increment-version
        with:
          version_type: 'rc'
          github_push_token: ${{ steps.app-token.outputs.token }}
