name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests and coverage
        run: ./gradlew koverXmlReportDebug

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./library/reports/kover/reportDebug.xml
          flags: unit
          name: codecov-unit
          token: ${{ secrets.CODECOV }}