name: Update version and publish to GitHub Packages (npm)

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID_GITHUB }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.event.release.target_commitish }}

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Update gradle.properties
        run: |
          sed -i "s/^version=.*/version=${VERSION}/" gradle.properties

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: gradle.properties

      - name: Commit updated version
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gradle.properties
          git commit -m "Updated version in gradle.properties to ${VERSION}"
          git push origin HEAD:${{ github.event.release.target_commitish }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew jsBrowserProductionWebpack

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hitoshura25'

      - name: Publish to GitHub Packages
        run: |
          cd build/js/packages/@hitoshura25/mpo-api-search-kmp
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}